const mongoose = require('mongoose');
const Question = require('./models/Question');
require('dotenv').config();

const newQuestions = [
  // LOGICAL REASONING (10)
  { content: 'Jika A > B dan B > C, pernyataan mana yang pasti benar?', concept_id: 'log_deductive', conceptName: 'Logika Deduktif', difficulty_level: 1, correct_answer: 'A > C', options: ['A = C', 'A < C', 'A > C', 'B > A'], explanation: 'Sifat transitif: jika A lebih besar dari B, dan B lebih besar dari C, maka A pasti lebih besar dari C.' },
  { content: 'Semua X adalah Y. Beberapa Y adalah Z. Kesimpulan?', concept_id: 'log_syllogism', conceptName: 'Silogisme', difficulty_level: 2, correct_answer: 'Tidak ada kesimpulan pasti', options: ['Semua X adalah Z', 'Beberapa X adalah Z', 'Tidak ada X yang Z', 'Tidak ada kesimpulan pasti'], explanation: 'Karena himpunan X ada di dalam Y, dan Z hanya beririsan dengan sebagian Y, Z belum tentu beririsan dengan X.' },
  { content: 'Jika hujan turun, jalanan basah. Jalanan tidak basah. Maka?', concept_id: 'log_conditional', conceptName: 'Logika Kondisional', difficulty_level: 3, correct_answer: 'Hujan tidak turun', options: ['Hujan turun deras', 'Hujan tidak turun', 'Jalanan kering karena panas', 'Tidak ada kesimpulan'], explanation: 'Modus Tollens: Jika P maka Q. Bukan Q, maka bukan P.' },
  { content: 'Dari 5 orang, Andi lebih tinggi dari Budi, tapi lebih pendek dari Coki. Dodi lebih tinggi dari Coki. Edi adalah yang terpendek. Siapa yang tertinggi?', concept_id: 'log_analytical', conceptName: 'Logika Analitis', difficulty_level: 3, correct_answer: 'Dodi', options: ['Andi', 'Budi', 'Coki', 'Dodi'], explanation: 'Urutan tinggi (tertinggi ke terpendek): Dodi, Coki, Andi, Budi, Edi.' },
  { content: 'Jika tidak ada anjing yang bisa terbang, dan semua burung bisa terbang. Kesimpulannya?', concept_id: 'log_syllogism', conceptName: 'Silogisme', difficulty_level: 2, correct_answer: 'Tidak ada anjing yang merupakan burung', options: ['Semua anjing adalah burung', 'Beberapa burung bukan anjing', 'Tidak ada anjing yang merupakan burung', 'Semua burung adalah anjing'], explanation: 'Himpunan yang bisa terbang dan himpunan anjing saling lepas. Karena burung masuk himpunan bisa terbang, tidak mungkin anjing adalah burung.' },
  { content: 'Enam orang duduk di meja bundar. P berseberangan dengan Q. R duduk di kanan Q. S berseberangan dengan R. T duduk di antara P dan R. Siapa di sebelah kiri Q?', concept_id: 'log_analytical', conceptName: 'Logika Analitis', difficulty_level: 5, correct_answer: 'U (orang keenam)', options: ['P', 'R', 'S', 'U (orang keenam)'], explanation: 'Menggambar posisi searah jarum jam: Q, R, T, P, S, U. Kiri Q adalah U.' },
  { content: 'Manakah dari pernyataan berikut yang merupakan paradoks?', concept_id: 'log_deductive', conceptName: 'Logika Deduktif', difficulty_level: 4, correct_answer: '"Pernyataan ini salah"', options: ['"Semua orang suka es krim"', '"Pernyataan ini salah"', '"Matahari terbit di barat"', '"1 + 1 = 3"'], explanation: 'Pernyataan "Pernyataan ini salah" menciptakan loop logika yang tidak memiliki nilai kebenaran stabil.' },
  { content: 'Tiga bersaudara, satu selalu jujur, satu selalu bohong, satu kadang-kadang. Jika si pembohong berkata "Aku anak tengah", si jujur berkata apa?', concept_id: 'log_analytical', conceptName: 'Logika Analitis', difficulty_level: 5, correct_answer: '"Dia berbohong"', options: ['"Dia jujur"', '"Dia berbohong"', '"Aku anak tengah"', 'Tidak bisa ditentukan'], explanation: 'Si jujur selalu mengatakan kebenaran. Jika si pembohong berbohong, si jujur akan menyatakan bahwa ucapan tersebut adalah bohong.' },
  { content: 'A implies B. B implies C. Not C implies?', concept_id: 'log_conditional', conceptName: 'Logika Kondisional', difficulty_level: 4, correct_answer: 'Not A', options: ['Not B', 'Not A', 'A', 'Both Not A and Not B'], explanation: 'Berdasarkan kontraposisi dan rantai implikasi, jika Not C maka Not B, dan jika Not B maka Not A.' },
  { content: 'Jika kamu belajar, kamu akan lulus. Kamu lulus. Apakah kamu pasti belajar?', concept_id: 'log_conditional', conceptName: 'Logika Kondisional', difficulty_level: 2, correct_answer: 'Tidak', options: ['Ya', 'Tidak', 'Mungkin', 'Pasti'], explanation: 'Afirmasi konsekuen adalah kelemahan logika. Lulus bisa saja karena alasan lain.' },

  // NUMERICAL ABILITY (10)
  { content: 'Berapa 15% dari 200?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 1, correct_answer: '30', options: ['15', '20', '30', '45'], explanation: '(15/100) * 200 = 30.' },
  { content: 'Jika 3x + 5 = 20, berapakah nilai x?', concept_id: 'num_algebra', conceptName: 'Aljabar', difficulty_level: 2, correct_answer: '5', options: ['3', '4', '5', '6'], explanation: '3x = 15, sehingga x = 5.' },
  { content: 'Dua dadu dilempar. Probabilitas jumlah angkanya 7 adalah?', concept_id: 'num_probability', conceptName: 'Probabilitas', difficulty_level: 4, correct_answer: '1/6', options: ['1/12', '1/6', '1/8', '7/36'], explanation: 'Ada 6 kombinasi dari 36 yang berjumlah 7 (1+6, 2+5, 3+4, 4+3, 5+2, 6+1). 6/36 = 1/6.' },
  { content: 'Luas lingkaran dengan jari-jari 10 cm adalah?', concept_id: 'num_geometry', conceptName: 'Geometri', difficulty_level: 2, correct_answer: '100π', options: ['10π', '20π', '50π', '100π'], explanation: 'Luas = π * r^2 = π * 10^2 = 100π.' },
  { content: 'Sebuah kereta menempuh jarak 120 km dalam 1.5 jam. Kecepatannya adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 3, correct_answer: '80 km/jam', options: ['60 km/jam', '80 km/jam', '90 km/jam', '100 km/jam'], explanation: 'Kecepatan = Jarak / Waktu = 120 / 1.5 = 80 km/jam.' },
  { content: 'Jika x^2 - y^2 = 24, dan x + y = 6, berapakah x - y?', concept_id: 'num_algebra', conceptName: 'Aljabar', difficulty_level: 4, correct_answer: '4', options: ['3', '4', '5', '6'], explanation: 'x^2 - y^2 = (x + y)(x - y). 24 = 6 * (x - y), maka x - y = 4.' },
  { content: 'Suku ke-10 dari deret 2, 5, 8, 11... adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 3, correct_answer: '29', options: ['26', '29', '32', '35'], explanation: 'Ini deret aritmatika dengan a=2, b=3. U10 = a + 9b = 2 + 27 = 29.' },
  { content: 'Harga baju didiskon 20%, lalu didiskon lagi 10%. Total diskon adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 4, correct_answer: '28%', options: ['30%', '28%', '25%', '22%'], explanation: 'Harga akhir = 0.8 * 0.9 = 0.72. Artinya total diskon 1 - 0.72 = 0.28 atau 28%.' },
  { content: 'Dari 10 orang, berapa banyak cara memilih komite 3 orang?', concept_id: 'num_probability', conceptName: 'Probabilitas', difficulty_level: 5, correct_answer: '120', options: ['30', '120', '360', '720'], explanation: 'Kombinasi 10C3 = 10! / (3! * 7!) = (10*9*8)/(3*2*1) = 120.' },
  { content: 'Volume kubus adalah 64 cm3. Luas permukaannya adalah?', concept_id: 'num_geometry', conceptName: 'Geometri', difficulty_level: 3, correct_answer: '96 cm2', options: ['32 cm2', '64 cm2', '96 cm2', '128 cm2'], explanation: 'Sisi = kubik root(64) = 4. Luas permukaan = 6 * s^2 = 6 * 16 = 96.' },

  // VERBAL INTELLIGENCE (10)
  { content: 'Manusia : Makan = Mobil : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 1, correct_answer: 'Bensin', options: ['Jalan', 'Bensin', 'Setir', 'Ban'], explanation: 'Mobil membutuhkan bensin untuk berfungsi layaknya manusia membutuhkan makan.' },
  { content: 'Antonim dari kata "EKLETIS" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 5, correct_answer: 'Eksklusif', options: ['Campuran', 'Tunggal', 'Eksklusif', 'Ortodoks'], explanation: 'Ekletis berarti memadukan berbagai sumber/aliran. Antonimnya adalah eksklusif atau murni/ortodoks (namun eksklusif sering kali jadi pilihan tepat di tes CPNS).' },
  { content: 'Kata "MENGKUDU" merupakan anagram dari?', concept_id: 'verb_vocab', conceptName: 'Kosa Kata', difficulty_level: 4, correct_answer: 'MENDUKUNG (minus N, G)', options: ['MENDUKUNG', 'MENGUDUD', 'KEMUDUNG', 'KUDUMENG'], explanation: 'Kosa kata anagram sering muncul.' },
  { content: 'Sinonim dari "EPHEMERAL" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 4, correct_answer: 'Sementara', options: ['Abadi', 'Sementara', 'Berkilau', 'Kosong'], explanation: 'Ephemeral berarti berlangsung sangat singkat.' },
  { content: 'Buku : Bab = Rumah : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 2, correct_answer: 'Ruangan', options: ['Atap', 'Ruangan', 'Keluarga', 'Cat'], explanation: 'Bab adalah bagian dalam buku, Ruangan adalah bagian dalam rumah.' },
  { content: 'Manakah kata yang tidak sebentuk dengan yang lain?', concept_id: 'verb_vocab', conceptName: 'Kosa Kata', difficulty_level: 3, correct_answer: 'Apel', options: ['Pisang', 'Jeruk', 'Apel', 'Kubis'], explanation: 'Kubis adalah sayuran, sisanya adalah buah.' },
  { content: 'Pohon : Hutan = Bintang : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 2, correct_answer: 'Galaksi', options: ['Malam', 'Langit', 'Galaksi', 'Bulan'], explanation: 'Kumpulan pohon membentuk hutan, kumpulan bintang membentuk galaksi.' },
  { content: 'Antonim dari "OBSEQUIOUS" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 5, correct_answer: 'Sombong', options: ['Penurut', 'Menjilat', 'Sombong', 'Ramah'], explanation: 'Obsequious berarti terlalu patuh/menjilat. Lawannya adalah sombong/mendominasi.' },
  { content: 'Panas : Membakar = Dingin : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 2, correct_answer: 'Membekukan', options: ['Mencairkan', 'Membekukan', 'Menyejukkan', 'Menggigil'], explanation: 'Tingkat ekstrem panas menyebabkan terbakar, tingkat ekstrem dingin menyebabkan beku.' },
  { content: 'Sinonim dari "PARADOKS" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 3, correct_answer: 'Kontradiksi', options: ['Kebohongan', 'Kebenaran', 'Kontradiksi', 'Fakta'], explanation: 'Paradoks berarti sesuatu yang seolah bertentangan dengan kebenaran (kontradiksi).' },

  // SPATIAL REASONING (10)
  { content: 'Jika huruf "d" diputar 180 derajat, menjadi huruf apa?', concept_id: 'spat_rotation', conceptName: 'Rotasi Bangun', difficulty_level: 1, correct_answer: 'p', options: ['b', 'q', 'p', 'd'], explanation: 'Putaran 180 derajat membuat titik berat di kanan bawah pindah ke kiri atas, oh tunggu, "d" diputar 180 = "p".' },
  { content: 'Berapa banyak kotak kecil pada kubus Rubik 3x3x3?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 3, correct_answer: '26 (tanpa inti) atau 27', options: ['27', '26', '54', '9'], explanation: 'Secara volume ada 3x3x3 = 27 kubus kecil.' },
  { content: 'Sebuah kertas dilipat setengah dua kali, lalu digunting ujungnya. Berapa banyak lubang jika dibuka?', concept_id: 'spat_pattern', conceptName: 'Pola Spasial', difficulty_level: 4, correct_answer: '1 lubang di tengah', options: ['1 lubang di tengah', '2 lubang', '4 lubang', 'Tidak ada lubang'], explanation: 'Menggunting ujung lipatan pusat akan menciptakan 1 lubang besar di tengah saat dibuka.' },
  { content: 'Bayangan cermin dari jarum jam 9:00 adalah pukul?', concept_id: 'spat_reflection', conceptName: 'Pencerminan', difficulty_level: 2, correct_answer: '3:00', options: ['9:00', '3:00', '6:00', '12:00'], explanation: 'Kiri menjadi kanan, jam 9 (jarum pendek di kiri) menjadi jam 3.' },
  { content: 'Jika dadu standar memiliki angka 1 berlawanan 6, 2 berlawanan 5, 3 berlawanan 4. Jika angka 2 di atas, dan 3 di depan, angka apa di kanan?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 5, correct_answer: '1', options: ['1', '4', '5', '6'], explanation: 'Berdasarkan orientasi dadu kanan, ini bergantung pada chiralitas dadu standar.' },
  { content: 'Bentuk bayangan cermin huruf "Z" mirip dengan angka?', concept_id: 'spat_reflection', conceptName: 'Pencerminan', difficulty_level: 2, correct_answer: 'Bukan angka, pola mirip S', options: ['2', '5', 'S', 'Bukan angka, pola mirip S'], explanation: 'Cermin Z arah miringnya berbalik.' },
  { content: 'Gambar mana yang dapat dilipat menjadi kubus sempurna?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 4, correct_answer: 'Pola salib', options: ['Pola L', 'Pola U', 'Pola T', 'Pola salib'], explanation: 'Pola jaring-jaring kubus standar berbentuk seperti salib (t-cross).' },
  { content: 'Rotasi huruf "M" 90 derajat searah jarum jam menjadi?', concept_id: 'spat_rotation', conceptName: 'Rotasi Bangun', difficulty_level: 2, correct_answer: 'E (mirip)', options: ['W', 'E (mirip)', '3', 'Tidak berubah'], explanation: 'Huruf M menjadi seperti E atau sigma terbalik.' },
  { content: 'Jika Anda melihat piramida tegak dari atas, bentuk apa yang terlihat?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 1, correct_answer: 'Persegi dengan dua diagonal', options: ['Segitiga', 'Persegi', 'Persegi dengan dua diagonal', 'Lingkaran'], explanation: 'Sisi piramida terlihat rata membentuk persegi dan rusuk tegaknya membentuk garis silang (diagonal).' },
  { content: 'Kertas persegi dipotong diagonal. Bentuk apa yang dihasilkan?', concept_id: 'spat_pattern', conceptName: 'Pola Spasial', difficulty_level: 1, correct_answer: 'Dua segitiga', options: ['Dua persegi panjang', 'Empat segitiga', 'Dua segitiga', 'Satu trapesium'], explanation: 'Potongan diagonal membagi persegi menjadi dua segitiga siku-siku sama kaki.' },

  // PATTERN RECOGNITION (10)
  { content: '1, 4, 9, 16, 25, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 1, correct_answer: '36', options: ['30', '35', '36', '49'], explanation: 'Ini adalah deret kuadrat sempurna (1^2, 2^2, 3^2...)' },
  { content: 'A, C, F, J, O, ... huruf selanjutnya?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 3, correct_answer: 'U', options: ['T', 'U', 'V', 'W'], explanation: 'Lompatan huruf bertambah 1: +2, +3, +4, +5, +6 (O + 6 = U).' },
  { content: '2, 3, 5, 8, 12, 17, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 2, correct_answer: '23', options: ['21', '22', '23', '24'], explanation: 'Lompatan: +1, +2, +3, +4, +5, selanjutnya +6 (17+6=23).' },
  { content: '1, 1, 2, 3, 5, 8, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 1, correct_answer: '13', options: ['10', '11', '12', '13'], explanation: 'Deret Fibonacci, 5 + 8 = 13.' },
  { content: 'Z, Y, X, W, V, ... huruf selanjutnya?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 1, correct_answer: 'U', options: ['T', 'U', 'S', 'R'], explanation: 'Urutan abjad mundur.' },
  { content: '3, 6, 12, 24, 48, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 2, correct_answer: '96', options: ['72', '84', '96', '120'], explanation: 'Pola perkalian 2.' },
  { content: 'A, Z, B, Y, C, ... huruf selanjutnya?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 2, correct_answer: 'X', options: ['D', 'X', 'W', 'V'], explanation: 'Dua deret diselang-seling: maju (A, B, C) dan mundur (Z, Y, X).' },
  { content: '1, 8, 27, 64, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 3, correct_answer: '125', options: ['100', '125', '144', '216'], explanation: 'Deret pangkat tiga (1^3, 2^3, 3^3, 4^3, 5^3).' },
  { content: '2, 6, 12, 20, 30, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 4, correct_answer: '42', options: ['40', '42', '44', '48'], explanation: 'Beda tingkat dua (Pola n*(n+1)). 6*7 = 42.' },
  { content: 'Jika O T T F F S S E ... selanjutnya apa?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 5, correct_answer: 'N', options: ['E', 'N', 'T', 'O'], explanation: 'Huruf depan angka Inggris: One, Two, Three, Four... S=Seven, E=Eight, N=Nine.' }
];

async function addData() {
  try {
    await mongoose.connect('mongodb://127.0.0.1:27017/eduagent');
    console.log('Connected to DB');
    await Question.insertMany(newQuestions);
    console.log(`Successfully added ${newQuestions.length} new questions!`);
    const count = await Question.countDocuments();
    console.log(`Total questions in DB: ${count}`);
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

addData();
