// 50 IQ Questions across 5 Categories (10 each)
const questions = [
  // ─── Logical Reasoning (10) ───────────────────────────────────
  { content: 'Jika semua Dokter adalah Manusia, dan beberapa Manusia adalah Kidal. Manakah pernyataan yang PASTI benar?', concept_id: 'logical_syllogism', conceptName: 'Logika Silogisme', difficulty_level: 2, correct_answer: 'Beberapa Manusia adalah Dokter', options: ['Semua Dokter adalah Kidal', 'Beberapa Dokter adalah Kidal', 'Beberapa Manusia adalah Dokter', 'Tidak ada Dokter yang Kidal'] },
  { content: 'Ali lebih tua dari Budi. Charlie lebih muda dari Budi. Dina lebih tua dari Ali. Siapakah yang paling muda?', concept_id: 'logical_ordering', conceptName: 'Logika Urutan', difficulty_level: 2, correct_answer: 'Charlie', options: ['Ali', 'Budi', 'Charlie', 'Dina'] },
  { content: 'Jika hari ini Senin, maka 100 hari lagi adalah hari apa?', concept_id: 'logical_calendar', conceptName: 'Logika Kalender', difficulty_level: 3, correct_answer: 'Rabu', options: ['Senin', 'Selasa', 'Rabu', 'Kamis'] },
  { content: 'Pernyataan: "Semua kucing hitam adalah hewan peliharaan." Manakah yang merupakan KONTRAPOSISI yang benar?', concept_id: 'logical_contraposition', conceptName: 'Logika Kontrapositif', difficulty_level: 4, correct_answer: 'Jika bukan hewan peliharaan, maka bukan kucing hitam', options: ['Jika hewan peliharaan, maka kucing hitam', 'Jika bukan kucing hitam, maka bukan peliharaan', 'Jika bukan hewan peliharaan, maka bukan kucing hitam', 'Semua hewan peliharaan adalah kucing hitam'] },
  { content: 'Beberapa mahasiswa menyukai matematika. Semua mahasiswa menyukai logika. Kesimpulan yang benar?', concept_id: 'logical_syllogism_2', conceptName: 'Logika Silogisme', difficulty_level: 3, correct_answer: 'Beberapa yang menyukai matematika juga menyukai logika', options: ['Semua yang menyukai matematika menyukai logika', 'Beberapa yang menyukai matematika juga menyukai logika', 'Tidak ada mahasiswa yang suka logika', 'Semua mahasiswa suka matematika'] },
  { content: 'Jika A > B dan C < B, maka pernyataan mana yang pasti benar?', concept_id: 'logical_inequality', conceptName: 'Logika Pertidaksamaan', difficulty_level: 1, correct_answer: 'A > C', options: ['A < C', 'C > A', 'A > C', 'B = C'] },
  { content: 'Dalam perlombaan lari, Anda menyalip pelari posisi kedua. Anda sekarang berada di posisi?', concept_id: 'logical_riddle', conceptName: 'Teka-teki Logika', difficulty_level: 1, correct_answer: 'Kedua', options: ['Pertama', 'Kedua', 'Ketiga', 'Terakhir'] },
  { content: 'Jika 5 mesin butuh 5 menit untuk membuat 5 barang, berapa waktu yang dibutuhkan 100 mesin untuk 100 barang?', concept_id: 'logical_riddle_2', conceptName: 'Teka-teki Logika', difficulty_level: 2, correct_answer: '5 Menit', options: ['100 Menit', '50 Menit', '5 Menit', '1 Menit'] },
  { content: 'Tidak ada angsa yang berwarna hijau. Beberapa burung berwarna hijau. Kesimpulan?', concept_id: 'logical_syllogism_3', conceptName: 'Logika Silogisme', difficulty_level: 3, correct_answer: 'Beberapa burung bukan angsa', options: ['Semua burung bukan angsa', 'Beberapa angsa adalah burung', 'Beberapa burung bukan angsa', 'Semua angsa adalah burung'] },
  { content: 'Semua M adalah N. Tidak ada N yang merupakan P. Apakah ada M yang merupakan P?', concept_id: 'logical_syllogism_4', conceptName: 'Logika Silogisme', difficulty_level: 3, correct_answer: 'Tidak Ada', options: ['Beberapa', 'Semua', 'Tidak Ada', 'Tidak bisa ditentukan'] },

  // ─── Numerical Ability (10) ───────────────────────────────────
  { content: 'Berapakah angka selanjutnya: 2, 6, 12, 20, 30, ...?', concept_id: 'num_series', conceptName: 'Deret Angka', difficulty_level: 2, correct_answer: '42', options: ['36', '40', '42', '48'] },
  { content: 'Jika harga sebuah barang naik 20%, lalu turun 20%, berapa persen perubahan dari harga awal?', concept_id: 'num_percent', conceptName: 'Persentase', difficulty_level: 3, correct_answer: 'Turun 4%', options: ['Tetap 0%', 'Turun 4%', 'Naik 4%', 'Turun 2%'] },
  { content: 'Sebuah jam menunjukkan pukul 3:15. Berapakah sudut antara jarum jam dan jarum menit?', concept_id: 'num_geometry', conceptName: 'Geometri Sudut', difficulty_level: 3, correct_answer: '7.5°', options: ['0°', '7.5°', '15°', '22.5°'] },
  { content: 'Sebuah kereta menempuh 120 km dalam 2 jam pertama, lalu 180 km dalam 3 jam berikutnya. Berapakah kecepatan rata-ratanya?', concept_id: 'num_speed', conceptName: 'Kecepatan Rata-rata', difficulty_level: 2, correct_answer: '60 km/jam', options: ['50 km/jam', '55 km/jam', '60 km/jam', '65 km/jam'] },
  { content: 'Harga baju didiskon 30% menjadi Rp 70.000. Berapa harga awalnya?', concept_id: 'num_algebra', conceptName: 'Aljabar Dasar', difficulty_level: 2, correct_answer: 'Rp 100.000', options: ['Rp 90.000', 'Rp 100.000', 'Rp 110.000', 'Rp 120.000'] },
  { content: 'Berapa 15% dari 200?', concept_id: 'num_basic_percent', conceptName: 'Persentase', difficulty_level: 1, correct_answer: '30', options: ['15', '20', '25', '30'] },
  { content: 'Akar kuadrat dari 144 dikalikan dengan 3 adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 1, correct_answer: '36', options: ['30', '32', '36', '48'] },
  { content: 'Dua buah dadu dilempar. Berapa peluang muncul jumlah angka 7?', concept_id: 'num_probability', conceptName: 'Peluang', difficulty_level: 4, correct_answer: '1/6', options: ['1/7', '1/6', '2/7', '1/12'] },
  { content: 'Jika X + Y = 10 dan X - Y = 4. Maka nilai X * Y adalah?', concept_id: 'num_equation', conceptName: 'Sistem Persamaan', difficulty_level: 3, correct_answer: '21', options: ['24', '21', '16', '10'] },
  { content: '½ + ¼ + ⅛ = ...?', concept_id: 'num_fraction', conceptName: 'Pecahan', difficulty_level: 2, correct_answer: '7/8', options: ['3/4', '5/8', '7/8', '1'] },

  // ─── Verbal Intelligence (10) ─────────────────────────────────
  { content: 'Temukan kata yang TIDAK termasuk kelompok: Apel, Mangga, Wortel, Pisang, Anggur', concept_id: 'verbal_classify', conceptName: 'Klasifikasi Verbal', difficulty_level: 1, correct_answer: 'Wortel', options: ['Apel', 'Mangga', 'Wortel', 'Anggur'] },
  { content: 'PANAS berbanding DINGIN sama seperti TINGGI berbanding ...?', concept_id: 'verbal_analogy', conceptName: 'Analogi Verbal', difficulty_level: 1, correct_answer: 'Rendah', options: ['Kecil', 'Rendah', 'Pendek', 'Bawah'] },
  { content: 'Temukan sinonim dari kata "ELUSIF":', concept_id: 'verbal_synonym', conceptName: 'Sinonim', difficulty_level: 3, correct_answer: 'Sulit ditangkap', options: ['Sangat indah', 'Sulit ditangkap', 'Mudah dipahami', 'Sangat besar'] },
  { content: '"Buah jatuh tidak jauh dari pohonnya." Apa makna peribahasa ini?', concept_id: 'verbal_proverb', conceptName: 'Pemahaman Peribahasa', difficulty_level: 2, correct_answer: 'Sifat anak mirip orang tuanya', options: ['Buah selalu jatuh ke bawah', 'Sifat anak mirip orang tuanya', 'Pohon yang kuat menghasilkan buah', 'Jangan menebang pohon berbuah'] },
  { content: 'Antonim dari "ABSTRAK" adalah?', concept_id: 'verbal_antonym', conceptName: 'Antonim', difficulty_level: 2, correct_answer: 'Konkret', options: ['Nyata', 'Konkret', 'Jelas', 'Kasar'] },
  { content: 'BACA : BUKU = MINUM : ...?', concept_id: 'verbal_analogy_2', conceptName: 'Analogi Verbal', difficulty_level: 1, correct_answer: 'Air', options: ['Gelas', 'Air', 'Makan', 'Haus'] },
  { content: 'Mana yang tidak masuk kelompok? Berlari, Berjalan, Melompat, Berpikir', concept_id: 'verbal_classify_2', conceptName: 'Klasifikasi Verbal', difficulty_level: 1, correct_answer: 'Berpikir', options: ['Berlari', 'Berjalan', 'Melompat', 'Berpikir'] },
  { content: 'Kata "PEDAGOGI" berkaitan erat dengan?', concept_id: 'verbal_vocabulary', conceptName: 'Kosakata', difficulty_level: 4, correct_answer: 'Pendidikan', options: ['Hukum', 'Kesehatan', 'Pendidikan', 'Agama'] },
  { content: 'Jika HURUF dirangkai menjadi KATA, maka KATA dirangkai menjadi?', concept_id: 'verbal_analogy_3', conceptName: 'Analogi Verbal', difficulty_level: 2, correct_answer: 'Kalimat', options: ['Paragraf', 'Kalimat', 'Buku', 'Bahasa'] },
  { content: 'Sinonim dari "KOMPREHENSIF" adalah?', concept_id: 'verbal_synonym_2', conceptName: 'Sinonim', difficulty_level: 3, correct_answer: 'Menyeluruh', options: ['Sempit', 'Singkat', 'Menyeluruh', 'Rumit'] },

  // ─── Spatial Reasoning (10) ───────────────────────────────────
  { content: 'Sebuah kubus memiliki 6 sisi. Jika dua kubus ditempelkan menjadi satu, berapa jumlah sisi yang terlihat dari luar?', concept_id: 'spatial_cube', conceptName: 'Visualisasi Ruang', difficulty_level: 2, correct_answer: '10', options: ['8', '10', '11', '12'] },
  { content: 'Bayangan cermin dari kata "AMBULANCE" yang terbaca dengan benar adalah karena ditulis secara...?', concept_id: 'spatial_mirror', conceptName: 'Bayangan Cermin', difficulty_level: 2, correct_answer: 'Terbalik horizontal (mirror)', options: ['Terbalik vertikal', 'Terbalik horizontal (mirror)', 'Diputar 180°', 'Ditulis normal'] },
  { content: 'Sebuah kertas dilipat dua kali lalu dilubangi di tengah. Berapa lubang yang muncul saat kertas dibuka?', concept_id: 'spatial_folding', conceptName: 'Paper Folding', difficulty_level: 3, correct_answer: '4', options: ['1', '2', '4', '8'] },
  { content: 'Jika Anda menghadap Utara, lalu berputar 90° searah jarum jam dua kali, Anda menghadap ke arah?', concept_id: 'spatial_direction', conceptName: 'Orientasi Arah', difficulty_level: 1, correct_answer: 'Selatan', options: ['Timur', 'Barat', 'Selatan', 'Utara'] },
  { content: 'Jika bangun bola dipotong tepat di tengah, bangun datar apa yang terbentuk pada potongan?', concept_id: 'spatial_slice', conceptName: 'Irisan Bangun Ruang', difficulty_level: 2, correct_answer: 'Lingkaran', options: ['Elips', 'Lingkaran', 'Persegi', 'Segitiga'] },
  { content: 'Anda menghadap ke Timur. Berputar 135° berlawanan arah jarum jam. Ke mana Anda menghadap sekarang?', concept_id: 'spatial_direction_2', conceptName: 'Orientasi Arah', difficulty_level: 3, correct_answer: 'Barat Laut', options: ['Timur Laut', 'Barat Daya', 'Barat Laut', 'Selatan'] },
  { content: 'Bayangan sebuah jam yang menunjukkan pukul 09:00 pada cermin datar akan menunjukkan pukul?', concept_id: 'spatial_mirror_2', conceptName: 'Bayangan Cermin', difficulty_level: 3, correct_answer: '03:00', options: ['09:00', '03:00', '08:00', '12:00'] },
  { content: 'Berapa banyak kubus kecil (1x1x1) yang diperlukan untuk membuat kubus besar (3x3x3)?', concept_id: 'spatial_volume', conceptName: 'Visualisasi Ruang', difficulty_level: 2, correct_answer: '27', options: ['9', '18', '27', '36'] },
  { content: 'Jika sisi depan sebuah dadu angka 4, sisi atas angka 2, sisi manakah yang berlawanan dengan angka 2? (standar dadu)', concept_id: 'spatial_dice', conceptName: 'Visualisasi Dadu', difficulty_level: 4, correct_answer: '5', options: ['1', '3', '5', '6'] },
  { content: 'Bentuk bayangan sebuah silinder yang disorot cahaya lurus dari samping adalah?', concept_id: 'spatial_shadow', conceptName: 'Bayangan 2D', difficulty_level: 2, correct_answer: 'Persegi panjang', options: ['Lingkaran', 'Persegi panjang', 'Segitiga', 'Elips'] },


  // LOGICAL REASONING (10)
  { content: 'Jika A > B dan B > C, pernyataan mana yang pasti benar?', concept_id: 'log_deductive', conceptName: 'Logika Deduktif', difficulty_level: 1, correct_answer: 'A > C', options: ['A = C', 'A < C', 'A > C', 'B > A'], explanation: 'Sifat transitif: jika A lebih besar dari B, dan B lebih besar dari C, maka A pasti lebih besar dari C.' },
  { content: 'Semua X adalah Y. Beberapa Y adalah Z. Kesimpulan?', concept_id: 'log_syllogism', conceptName: 'Silogisme', difficulty_level: 2, correct_answer: 'Tidak ada kesimpulan pasti', options: ['Semua X adalah Z', 'Beberapa X adalah Z', 'Tidak ada X yang Z', 'Tidak ada kesimpulan pasti'], explanation: 'Karena himpunan X ada di dalam Y, dan Z hanya beririsan dengan sebagian Y, Z belum tentu beririsan dengan X.' },
  { content: 'Jika hujan turun, jalanan basah. Jalanan tidak basah. Maka?', concept_id: 'log_conditional', conceptName: 'Logika Kondisional', difficulty_level: 3, correct_answer: 'Hujan tidak turun', options: ['Hujan turun deras', 'Hujan tidak turun', 'Jalanan kering karena panas', 'Tidak ada kesimpulan'], explanation: 'Modus Tollens: Jika P maka Q. Bukan Q, maka bukan P.' },
  { content: 'Dari 5 orang, Andi lebih tinggi dari Budi, tapi lebih pendek dari Coki. Dodi lebih tinggi dari Coki. Edi adalah yang terpendek. Siapa yang tertinggi?', concept_id: 'log_analytical', conceptName: 'Logika Analitis', difficulty_level: 3, correct_answer: 'Dodi', options: ['Andi', 'Budi', 'Coki', 'Dodi'], explanation: 'Urutan tinggi (tertinggi ke terpendek): Dodi, Coki, Andi, Budi, Edi.' },
  { content: 'Jika tidak ada anjing yang bisa terbang, dan semua burung bisa terbang. Kesimpulannya?', concept_id: 'log_syllogism', conceptName: 'Silogisme', difficulty_level: 2, correct_answer: 'Tidak ada anjing yang merupakan burung', options: ['Semua anjing adalah burung', 'Beberapa burung bukan anjing', 'Tidak ada anjing yang merupakan burung', 'Semua burung adalah anjing'], explanation: 'Himpunan yang bisa terbang dan himpunan anjing saling lepas. Karena burung masuk himpunan bisa terbang, tidak mungkin anjing adalah burung.' },
  { content: 'Enam orang duduk di meja bundar. P berseberangan dengan Q. R duduk di kanan Q. S berseberangan dengan R. T duduk di antara P dan R. Siapa di sebelah kiri Q?', concept_id: 'log_analytical', conceptName: 'Logika Analitis', difficulty_level: 5, correct_answer: 'U (orang keenam)', options: ['P', 'R', 'S', 'U (orang keenam)'], explanation: 'Menggambar posisi searah jarum jam: Q, R, T, P, S, U. Kiri Q adalah U.' },
  { content: 'Manakah dari pernyataan berikut yang merupakan paradoks?', concept_id: 'log_deductive', conceptName: 'Logika Deduktif', difficulty_level: 4, correct_answer: '"Pernyataan ini salah"', options: ['"Semua orang suka es krim"', '"Pernyataan ini salah"', '"Matahari terbit di barat"', '"1 + 1 = 3"'], explanation: 'Pernyataan "Pernyataan ini salah" menciptakan loop logika yang tidak memiliki nilai kebenaran stabil.' },
  { content: 'Tiga bersaudara, satu selalu jujur, satu selalu bohong, satu kadang-kadang. Jika si pembohong berkata "Aku anak tengah", si jujur berkata apa?', concept_id: 'log_analytical', conceptName: 'Logika Analitis', difficulty_level: 5, correct_answer: '"Dia berbohong"', options: ['"Dia jujur"', '"Dia berbohong"', '"Aku anak tengah"', 'Tidak bisa ditentukan'], explanation: 'Si jujur selalu mengatakan kebenaran. Jika si pembohong berbohong, si jujur akan menyatakan bahwa ucapan tersebut adalah bohong.' },
  { content: 'A implies B. B implies C. Not C implies?', concept_id: 'log_conditional', conceptName: 'Logika Kondisional', difficulty_level: 4, correct_answer: 'Not A', options: ['Not B', 'Not A', 'A', 'Both Not A and Not B'], explanation: 'Berdasarkan kontraposisi dan rantai implikasi, jika Not C maka Not B, dan jika Not B maka Not A.' },
  { content: 'Jika kamu belajar, kamu akan lulus. Kamu lulus. Apakah kamu pasti belajar?', concept_id: 'log_conditional', conceptName: 'Logika Kondisional', difficulty_level: 2, correct_answer: 'Tidak', options: ['Ya', 'Tidak', 'Mungkin', 'Pasti'], explanation: 'Afirmasi konsekuen adalah kelemahan logika. Lulus bisa saja karena alasan lain.' },

  // NUMERICAL ABILITY (10)
  { content: 'Berapa 15% dari 200?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 1, correct_answer: '30', options: ['15', '20', '30', '45'], explanation: '(15/100) * 200 = 30.' },
  { content: 'Jika 3x + 5 = 20, berapakah nilai x?', concept_id: 'num_algebra', conceptName: 'Aljabar', difficulty_level: 2, correct_answer: '5', options: ['3', '4', '5', '6'], explanation: '3x = 15, sehingga x = 5.' },
  { content: 'Dua dadu dilempar. Probabilitas jumlah angkanya 7 adalah?', concept_id: 'num_probability', conceptName: 'Probabilitas', difficulty_level: 4, correct_answer: '1/6', options: ['1/12', '1/6', '1/8', '7/36'], explanation: 'Ada 6 kombinasi dari 36 yang berjumlah 7 (1+6, 2+5, 3+4, 4+3, 5+2, 6+1). 6/36 = 1/6.' },
  { content: 'Luas lingkaran dengan jari-jari 10 cm adalah?', concept_id: 'num_geometry', conceptName: 'Geometri', difficulty_level: 2, correct_answer: '100π', options: ['10π', '20π', '50π', '100π'], explanation: 'Luas = π * r^2 = π * 10^2 = 100π.' },
  { content: 'Sebuah kereta menempuh jarak 120 km dalam 1.5 jam. Kecepatannya adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 3, correct_answer: '80 km/jam', options: ['60 km/jam', '80 km/jam', '90 km/jam', '100 km/jam'], explanation: 'Kecepatan = Jarak / Waktu = 120 / 1.5 = 80 km/jam.' },
  { content: 'Jika x^2 - y^2 = 24, dan x + y = 6, berapakah x - y?', concept_id: 'num_algebra', conceptName: 'Aljabar', difficulty_level: 4, correct_answer: '4', options: ['3', '4', '5', '6'], explanation: 'x^2 - y^2 = (x + y)(x - y). 24 = 6 * (x - y), maka x - y = 4.' },
  { content: 'Suku ke-10 dari deret 2, 5, 8, 11... adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 3, correct_answer: '29', options: ['26', '29', '32', '35'], explanation: 'Ini deret aritmatika dengan a=2, b=3. U10 = a + 9b = 2 + 27 = 29.' },
  { content: 'Harga baju didiskon 20%, lalu didiskon lagi 10%. Total diskon adalah?', concept_id: 'num_arithmetic', conceptName: 'Aritmatika', difficulty_level: 4, correct_answer: '28%', options: ['30%', '28%', '25%', '22%'], explanation: 'Harga akhir = 0.8 * 0.9 = 0.72. Artinya total diskon 1 - 0.72 = 0.28 atau 28%.' },
  { content: 'Dari 10 orang, berapa banyak cara memilih komite 3 orang?', concept_id: 'num_probability', conceptName: 'Probabilitas', difficulty_level: 5, correct_answer: '120', options: ['30', '120', '360', '720'], explanation: 'Kombinasi 10C3 = 10! / (3! * 7!) = (10*9*8)/(3*2*1) = 120.' },
  { content: 'Volume kubus adalah 64 cm3. Luas permukaannya adalah?', concept_id: 'num_geometry', conceptName: 'Geometri', difficulty_level: 3, correct_answer: '96 cm2', options: ['32 cm2', '64 cm2', '96 cm2', '128 cm2'], explanation: 'Sisi = kubik root(64) = 4. Luas permukaan = 6 * s^2 = 6 * 16 = 96.' },

  // VERBAL INTELLIGENCE (10)
  { content: 'Manusia : Makan = Mobil : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 1, correct_answer: 'Bensin', options: ['Jalan', 'Bensin', 'Setir', 'Ban'], explanation: 'Mobil membutuhkan bensin untuk berfungsi layaknya manusia membutuhkan makan.' },
  { content: 'Antonim dari kata "EKLETIS" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 5, correct_answer: 'Eksklusif', options: ['Campuran', 'Tunggal', 'Eksklusif', 'Ortodoks'], explanation: 'Ekletis berarti memadukan berbagai sumber/aliran. Antonimnya adalah eksklusif atau murni/ortodoks (namun eksklusif sering kali jadi pilihan tepat di tes CPNS).' },
  { content: 'Kata "MENGKUDU" merupakan anagram dari?', concept_id: 'verb_vocab', conceptName: 'Kosa Kata', difficulty_level: 4, correct_answer: 'MENDUKUNG (minus N, G)', options: ['MENDUKUNG', 'MENGUDUD', 'KEMUDUNG', 'KUDUMENG'], explanation: 'Kosa kata anagram sering muncul.' },
  { content: 'Sinonim dari "EPHEMERAL" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 4, correct_answer: 'Sementara', options: ['Abadi', 'Sementara', 'Berkilau', 'Kosong'], explanation: 'Ephemeral berarti berlangsung sangat singkat.' },
  { content: 'Buku : Bab = Rumah : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 2, correct_answer: 'Ruangan', options: ['Atap', 'Ruangan', 'Keluarga', 'Cat'], explanation: 'Bab adalah bagian dalam buku, Ruangan adalah bagian dalam rumah.' },
  { content: 'Manakah kata yang tidak sebentuk dengan yang lain?', concept_id: 'verb_vocab', conceptName: 'Kosa Kata', difficulty_level: 3, correct_answer: 'Apel', options: ['Pisang', 'Jeruk', 'Apel', 'Kubis'], explanation: 'Kubis adalah sayuran, sisanya adalah buah.' },
  { content: 'Pohon : Hutan = Bintang : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 2, correct_answer: 'Galaksi', options: ['Malam', 'Langit', 'Galaksi', 'Bulan'], explanation: 'Kumpulan pohon membentuk hutan, kumpulan bintang membentuk galaksi.' },
  { content: 'Antonim dari "OBSEQUIOUS" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 5, correct_answer: 'Sombong', options: ['Penurut', 'Menjilat', 'Sombong', 'Ramah'], explanation: 'Obsequious berarti terlalu patuh/menjilat. Lawannya adalah sombong/mendominasi.' },
  { content: 'Panas : Membakar = Dingin : ?', concept_id: 'verb_analogy', conceptName: 'Analogi Kata', difficulty_level: 2, correct_answer: 'Membekukan', options: ['Mencairkan', 'Membekukan', 'Menyejukkan', 'Menggigil'], explanation: 'Tingkat ekstrem panas menyebabkan terbakar, tingkat ekstrem dingin menyebabkan beku.' },
  { content: 'Sinonim dari "PARADOKS" adalah?', concept_id: 'verb_syn_ant', conceptName: 'Sinonim/Antonim', difficulty_level: 3, correct_answer: 'Kontradiksi', options: ['Kebohongan', 'Kebenaran', 'Kontradiksi', 'Fakta'], explanation: 'Paradoks berarti sesuatu yang seolah bertentangan dengan kebenaran (kontradiksi).' },

  // SPATIAL REASONING (10)
  { content: 'Jika huruf "d" diputar 180 derajat, menjadi huruf apa?', concept_id: 'spat_rotation', conceptName: 'Rotasi Bangun', difficulty_level: 1, correct_answer: 'p', options: ['b', 'q', 'p', 'd'], explanation: 'Putaran 180 derajat membuat titik berat di kanan bawah pindah ke kiri atas, oh tunggu, "d" diputar 180 = "p".' },
  { content: 'Berapa banyak kotak kecil pada kubus Rubik 3x3x3?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 3, correct_answer: '26 (tanpa inti) atau 27', options: ['27', '26', '54', '9'], explanation: 'Secara volume ada 3x3x3 = 27 kubus kecil.' },
  { content: 'Sebuah kertas dilipat setengah dua kali, lalu digunting ujungnya. Berapa banyak lubang jika dibuka?', concept_id: 'spat_pattern', conceptName: 'Pola Spasial', difficulty_level: 4, correct_answer: '1 lubang di tengah', options: ['1 lubang di tengah', '2 lubang', '4 lubang', 'Tidak ada lubang'], explanation: 'Menggunting ujung lipatan pusat akan menciptakan 1 lubang besar di tengah saat dibuka.' },
  { content: 'Bayangan cermin dari jarum jam 9:00 adalah pukul?', concept_id: 'spat_reflection', conceptName: 'Pencerminan', difficulty_level: 2, correct_answer: '3:00', options: ['9:00', '3:00', '6:00', '12:00'], explanation: 'Kiri menjadi kanan, jam 9 (jarum pendek di kiri) menjadi jam 3.' },
  { content: 'Jika dadu standar memiliki angka 1 berlawanan 6, 2 berlawanan 5, 3 berlawanan 4. Jika angka 2 di atas, dan 3 di depan, angka apa di kanan?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 5, correct_answer: '1', options: ['1', '4', '5', '6'], explanation: 'Berdasarkan orientasi dadu kanan, ini bergantung pada chiralitas dadu standar.' },
  { content: 'Bentuk bayangan cermin huruf "Z" mirip dengan angka?', concept_id: 'spat_reflection', conceptName: 'Pencerminan', difficulty_level: 2, correct_answer: 'Bukan angka, pola mirip S', options: ['2', '5', 'S', 'Bukan angka, pola mirip S'], explanation: 'Cermin Z arah miringnya berbalik.' },
  { content: 'Gambar mana yang dapat dilipat menjadi kubus sempurna?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 4, correct_answer: 'Pola salib', options: ['Pola L', 'Pola U', 'Pola T', 'Pola salib'], explanation: 'Pola jaring-jaring kubus standar berbentuk seperti salib (t-cross).' },
  { content: 'Rotasi huruf "M" 90 derajat searah jarum jam menjadi?', concept_id: 'spat_rotation', conceptName: 'Rotasi Bangun', difficulty_level: 2, correct_answer: 'E (mirip)', options: ['W', 'E (mirip)', '3', 'Tidak berubah'], explanation: 'Huruf M menjadi seperti E atau sigma terbalik.' },
  { content: 'Jika Anda melihat piramida tegak dari atas, bentuk apa yang terlihat?', concept_id: 'spat_3d', conceptName: 'Visualisasi 3D', difficulty_level: 1, correct_answer: 'Persegi dengan dua diagonal', options: ['Segitiga', 'Persegi', 'Persegi dengan dua diagonal', 'Lingkaran'], explanation: 'Sisi piramida terlihat rata membentuk persegi dan rusuk tegaknya membentuk garis silang (diagonal).' },
  { content: 'Kertas persegi dipotong diagonal. Bentuk apa yang dihasilkan?', concept_id: 'spat_pattern', conceptName: 'Pola Spasial', difficulty_level: 1, correct_answer: 'Dua segitiga', options: ['Dua persegi panjang', 'Empat segitiga', 'Dua segitiga', 'Satu trapesium'], explanation: 'Potongan diagonal membagi persegi menjadi dua segitiga siku-siku sama kaki.' },

  // PATTERN RECOGNITION (10)
  { content: '1, 4, 9, 16, 25, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 1, correct_answer: '36', options: ['30', '35', '36', '49'], explanation: 'Ini adalah deret kuadrat sempurna (1^2, 2^2, 3^2...)' },
  { content: 'A, C, F, J, O, ... huruf selanjutnya?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 3, correct_answer: 'U', options: ['T', 'U', 'V', 'W'], explanation: 'Lompatan huruf bertambah 1: +2, +3, +4, +5, +6 (O + 6 = U).' },
  { content: '2, 3, 5, 8, 12, 17, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 2, correct_answer: '23', options: ['21', '22', '23', '24'], explanation: 'Lompatan: +1, +2, +3, +4, +5, selanjutnya +6 (17+6=23).' },
  { content: '1, 1, 2, 3, 5, 8, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 1, correct_answer: '13', options: ['10', '11', '12', '13'], explanation: 'Deret Fibonacci, 5 + 8 = 13.' },
  { content: 'Z, Y, X, W, V, ... huruf selanjutnya?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 1, correct_answer: 'U', options: ['T', 'U', 'S', 'R'], explanation: 'Urutan abjad mundur.' },
  { content: '3, 6, 12, 24, 48, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 2, correct_answer: '96', options: ['72', '84', '96', '120'], explanation: 'Pola perkalian 2.' },
  { content: 'A, Z, B, Y, C, ... huruf selanjutnya?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 2, correct_answer: 'X', options: ['D', 'X', 'W', 'V'], explanation: 'Dua deret diselang-seling: maju (A, B, C) dan mundur (Z, Y, X).' },
  { content: '1, 8, 27, 64, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 3, correct_answer: '125', options: ['100', '125', '144', '216'], explanation: 'Deret pangkat tiga (1^3, 2^3, 3^3, 4^3, 5^3).' },
  { content: '2, 6, 12, 20, 30, ... angka selanjutnya?', concept_id: 'patt_number', conceptName: 'Deret Angka', difficulty_level: 4, correct_answer: '42', options: ['40', '42', '44', '48'], explanation: 'Beda tingkat dua (Pola n*(n+1)). 6*7 = 42.' },
  { content: 'Jika O T T F F S S E ... selanjutnya apa?', concept_id: 'patt_letter', conceptName: 'Deret Huruf', difficulty_level: 5, correct_answer: 'N', options: ['E', 'N', 'T', 'O'], explanation: 'Huruf depan angka Inggris: One, Two, Three, Four... S=Seven, E=Eight, N=Nine.' },

  // ─── Pattern Recognition (10) ─────────────────────────────────
  { content: 'Apa angka selanjutnya pada pola: 1, 1, 2, 3, 5, 8, 13, ...?', concept_id: 'pattern_fibonacci', conceptName: 'Deret Fibonacci', difficulty_level: 2, correct_answer: '21', options: ['18', '20', '21', '24'] },
  { content: 'Jika A=1, B=2, C=3, dst. Berapakah nilai dari kata "CAB"?', concept_id: 'pattern_code', conceptName: 'Enkripsi Pola', difficulty_level: 1, correct_answer: '6', options: ['5', '6', '7', '8'] },
  { content: 'Deret: 3, 9, 27, 81, ...? Angka selanjutnya adalah:', concept_id: 'pattern_geometric', conceptName: 'Deret Geometri', difficulty_level: 2, correct_answer: '243', options: ['162', '216', '243', '324'] },
  { content: 'Jika "FISH" dikodekan sebagai "EHRG", maka "BIRD" dikodekan sebagai?', concept_id: 'pattern_cipher', conceptName: 'Sandi Caesar', difficulty_level: 3, correct_answer: 'AHQC', options: ['AHQC', 'CJSE', 'AKSD', 'BHQD'] },
  { content: 'A, C, F, J, O, ... Huruf selanjutnya adalah?', concept_id: 'pattern_alphabet', conceptName: 'Deret Alfabet', difficulty_level: 3, correct_answer: 'U', options: ['T', 'U', 'V', 'W'] },
  { content: '1, 4, 9, 16, 25, ... Angka berikutnya?', concept_id: 'pattern_square', conceptName: 'Deret Kuadrat', difficulty_level: 1, correct_answer: '36', options: ['30', '32', '36', '40'] },
  { content: 'O, T, T, F, F, S, S, E, N, ... Huruf berikutnya?', concept_id: 'pattern_riddle', conceptName: 'Pola Teka-teki', difficulty_level: 4, correct_answer: 'T', options: ['T', 'E', 'O', 'N'] },
  { content: '121, 144, 169, 196, ... Angka berikutnya?', concept_id: 'pattern_square_2', conceptName: 'Deret Kuadrat', difficulty_level: 2, correct_answer: '225', options: ['215', '225', '256', '289'] },
  { content: 'Jika APPLE = 5, BANANA = 6, STRAWBERRY = 10, maka MANGO = ?', concept_id: 'pattern_count', conceptName: 'Pola Perhitungan', difficulty_level: 1, correct_answer: '5', options: ['4', '5', '6', '7'] },
  { content: '2, 3, 5, 7, 11, 13, ... Angka berikutnya?', concept_id: 'pattern_prime', conceptName: 'Deret Prima', difficulty_level: 2, correct_answer: '17', options: ['15', '17', '19', '21'] },
];

const logicalResources = require('./seedContent/logical');
const numericalResources = require('./seedContent/numerical');
const verbalResources = require('./seedContent/verbal');
const spatialResources = require('./seedContent/spatial');
const patternResources = require('./seedContent/pattern');

const resources = [
  ...logicalResources,
  ...numericalResources,
  ...verbalResources,
  ...spatialResources,
  ...patternResources
];

module.exports = { questions, resources };
